[project]
name = "cli-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.7",
    "prompt-toolkit>=3.0.52",
    "rich>=14.2.0",
]
